server:
  servlet:
    context-path: /admin

spring:
  application:
    name: commerce-admin

  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: demo
    password: demo

